language: node_js
node_js:
  - 13

services:
  - docker

install:
  - echo 'no installation required'

before_script:
  - echo "no tests"

script:
  - docker --version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed 06122019/udagram-api-feed
  - docker tag udagram-api-user 06122019/udagram-api-user
  - docker tag udagram-frontend 06122019/udagram-frontend:local
  - docker tag udagram-reverseproxy 06122019/udagram-reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 06122019/udagram-api-feed
  - docker push 06122019/udagram-api-user
  - docker push 06122019/udagram-frontend:local
  - docker push 06122019/udagram-reverseproxy
